### ISSUE TITLE
UI remake

### ISSUE THREAD

**Issue by roramigator** [roramigator/Aqro#1]
User interface remodeling.

**Comment by roramigator** [comment]
All is functional so far but interfaces are not my forte, I used Bootstrap for UI but I would like to remake the interface. @kniziol

**Comment by kniziol** [comment]
@roramigator Could you tell more? Which part of UI would you like to remake?

**Comment by roramigator** [comment]
Just the front view, I asked for feedback from a few friends and I was told that seems "too plain, almost empty" @kniziol

**Comment by kniziol** [comment]
I can take a look at the UI/design. Could you provide url address?

**Comment by roramigator** [comment]
let me upload it, give me a few minutes

**Comment by kniziol** [comment]
Did you upload it? Could you share/paste address?

**Comment by roramigator** [comment]
Here it is... https://440.000webhostapp.com

**Comment by kniziol** [comment]
Well, UI looks rough.

1. It's based on [Bootstrap](https://getbootstrap.com) v3.3.5 (currently v4.3.1).
2. Buttons with icons only, without names, looks strange, because user don't know what they do.
3. There are missing communiques, e.g. "after data save.

What are your expectations? What can I do for you? 🙂

**Comment by roramigator** [comment]
Well, I don't mind the functionalities that already has (I'm also adding more) but, as you say; my main concern is the UI, perhaps you can help me reconstruction of it.

**Comment by kniziol** [comment]
Yes, I can. Do you agree to implement latest version of Bootstrap (v4.3.1)?

**Comment by roramigator** [comment]
Absolutely

**Comment by kniziol** [comment]
Great. Assign me to the task/issue, please. I will prepare a pull request.

**Comment by roramigator** [comment]
If you have any questions feel free to contact me.

**Comment by kniziol** [comment]
I've created #2 PR with UI based on Bootstrap 4.x. Could you approve?

**Comment by roramigator** [comment]
Done.

**Comment by kniziol** [comment]
Thank you

**Comment by roramigator** [comment]
Thank _you_.

**Comment by kniziol** [comment]
Could you approve #2 and close this issue? 🙃

**Comment by roramigator** [comment]
Ups...
